apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: event-greeter-listener
spec:
  serviceAccountName: tekton-robot
  triggers:
    - name: event-greeter-trigger
      bindings:
        - ref: event-greeter-binding
      template:
        ref: event-greeter-template
