apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: arithmetic-results-pipeline
spec:
  params:
    - name: value1
    - name: value2
  tasks:
    - name: arithmetic-calculator
      taskRef:
        name: arithmetic-result-calculator
      params:
        - name: value1
          value: $(params.value1)
        - name: value2
          value: $(params.value2)
    - name: arithmetic-answer-echoer
      taskRef:
        name: arithmetic-result-printer
      params:
        - name: arithmetic-result
          value: $(tasks.arithmetic-calculator.results.summed-value)
        - name: value1
          value: $(params.value1)
        - name: value2
          value: $(params.value2)
      runAfter:
        - arithmetic-calculator
