apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: arithmetic-results-pipeline-run
spec:
  pipelineRef:
    name: arithmetic-results-pipeline
  params:
    - name: value1
      value: 3
    - name: value2
      value: 7
