apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: arithmetic-result-calculator
spec:
  params:
    - name: value1
      description: 'The first number to be summed.'
    - name: value2
      description: 'The second number to be summed.'
  results:
    - name: summed-value
      description: 'The summed value of value1 and value2.'
  steps:
    - name: calculate-result
      image: busybox:stable
      script: |
        #!/bin/sh
        result=$(( $(params.value1) + $(params.value2) ))
        echo -n $result > $(results.summed-value.path)
        echo "We are done calculating the sum of $(params.value1) and $(params.value2)"

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: arithmetic-result-printer
spec:
  params:
    - name: arithmetic-result
    - name: value1
      description: 'The first number that was summed.'
    - name: value2
      description: 'The second number that was summed.'
  steps:
    - name: print-result
      image: busybox:stable
      script: |
        #!/bin/sh
        echo "The sum of $(params.value1) and $(params.value2) is $(params.arithmetic-result) !"
