apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: dynastic-pipeline-run
spec:
  pipelineRef:
    name: dynastic-pipeline
  workspaces:
    - name: mwenemutapa
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 500Mi

    - name: nguni
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 500Mi
