apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: dynastic-pipeline-run
spec:
  pipelineRef:
    name: dynastic-pipeline
  workspaces:
    - name: mwenemutapa
      emptyDir: {}
    - name: nguni
      emptyDir: {}
