apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: command-looper-task
spec:
  params:
    - name: commands
      description: 'The commands to be looped.'
      type: array
  steps:
    - name: loop-array-commands
      image: alpine
      args: ["$(params.commands[*])"]
      script: |
        #!/bin/sh
        for cmd in "$@"; do
          eval "$cmd"
        done