apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: docker-command-tests
spec:
  steps:
    - name: docker-command-step
      image: docker
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
      script: |
        #!/bin/sh
        docker image ls >> docker.txt

        cat docker.txt
  volumes:
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
