apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-repo-cloning
spec:
  workspaces:
    - name: git-trigger-home
  params:
    - name: gitrepo
      type: string
      description: 'The repo to be cloned'
  steps:
    - name: git-clone
      image: alpine/git
      script: |
        #!/bin/sh
        git clone $(params.gitrepo) $(workspaces.git-trigger-home.path)/repo