apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: git-trigger-pipeline
spec:
  workspaces:
    - name: git-trigger-home
  tasks:
    - name: git-repo-cloning-executor
      workspaces:
        - name: git-trigger-home
          workspace: git-trigger-home
      taskRef:
        name: git-repo-cloning
    - name: repository-pre-build-script-executor
      workspaces:
        - name: git-trigger-home
          workspace: git-trigger-home
      taskRef:
        name: pre-build-script-tasks
      runAfter:
        - git-repo-cloning-executor
