apiVersion: v1
kind: Secret
metadata:
  name: github-interceptor-secret
type: Opaque
stringData:
  secretToken: 3164970

---
apiVersion: v1
kind: Secret
metadata:
  name: repo-env-variables
type: Opaque
stringData:
  existingUserToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJSZWZpbHdlIiwibGFzdE5hbWUiOiJQaGFnbyIsImVtYWlsIjoicmVmaWx3ZUBtb2NrLmNvbSJ9.LKYiS9Wwa2Pid7lze5YY7FEtkiCJomIVPvHamB9qCsA
  nonExistantUserToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJTaW1taSIsImxhc3ROYW1lIjoiTWRhIiwiZW1haWwiOiJzaW1taUBtb2NrLmNvbSJ9.Os3YQk4iJynm3_Z0z80bHE49Z5iZynjBqPeG1IJ9K7o
