apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-greeter
spec:
  params:
    - name: greeters-name
      description: 'The name of the user triggering the greeting.'
      default: 'Changamire'
    - name: territory
      description: 'The territory to be conquered by the greeter.'
      default: 'The world'
  steps:
    - name: greet-the-world
      image: alpine
      script: |
        #!/bin/sh
        echo "Greeting $(params.greeters-name), from the Basic Task!!!"
        echo "$(params.territory) is yours to conquer!"
